#npmRegistryServer: "http://localhost:4873"
#unsafeHttpWhitelist:
#  - localhost
#

npmRegistryServer: "http://npmreg.informaticsint.com:4873/"
unsafeHttpWhitelist:
  - npmreg.informaticsint.com:4873
